name: Bump Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump patch version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version patch -m "ci: bump version to %s [skip ci]"
          git push --follow-tags origin main

      - name: Force-sync deployment branch
        run: |
          git fetch origin main
          git branch -f deployment main
          git push origin deployment --force
