name: Notify Discord on Deployment Push

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  discord-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Build Discord embeds and send
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK }}
        run: |
          REPO="${GITHUB_REPOSITORY}"
          BRANCH=$(jq -r .ref "$GITHUB_EVENT_PATH" | sed 's#refs/heads/##')
          COMPARE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/compare/${{ github.event.before }}...${{ github.sha }}"

          # Format all commits into bullet lines
          COMMITS=$(jq -r '.commits[] | "- [`\(.id[0:7])`](\(.url)) **\(.message | gsub("\n"; " "))** — \(.author.name)"' "$GITHUB_EVENT_PATH")

          # Break into multiple embeds if necessary
          DESC="**Repository:** [${REPO}](${GITHUB_SERVER_URL}/${REPO})\\n**Branch:** \`${BRANCH}\`\\n**Pusher:** ${GITHUB_ACTOR}\\n\\n**Commits:**\\n"
          TMP_DESC=""
          COUNT=0
          i=0
          mkdir embeds

          while IFS= read -r line; do
            TMP_DESC="${TMP_DESC}${line}\\n"
            COUNT=$((COUNT + ${#line}))
            if [ $COUNT -ge 1500 ]; then
              i=$((i+1))
              cat <<EOF > embeds/embed_$i.json
              {
                "title": "🚀 Deployment Branch Updated (Part $i)",
                "description": "${DESC}${TMP_DESC}\\n[View Changes](${COMPARE_URL})",
                "color": 5814783,
                "footer": { "text": "GitHub Actions • Deployment Push" },
                "timestamp": "$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
              }
EOF
              TMP_DESC=""
              COUNT=0
            fi
          done <<< "$COMMITS"

          # Final embed if remaining text exists
          if [ -n "$TMP_DESC" ]; then
            i=$((i+1))
            cat <<EOF > embeds/embed_$i.json
            {
              "title": "🚀 Deployment Branch Updated (Part $i)",
              "description": "${DESC}${TMP_DESC}\\n[View Changes](${COMPARE_URL})",
              "color": 5814783,
              "footer": { "text": "GitHub Actions • Deployment Push" },
              "timestamp": "$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
            }
EOF
          fi

          # Combine all embeds into one JSON payload
          jq -s '{embeds: .}' embeds/embed_*.json > payload.json
          cat payload.json

          # Send to Discord
          curl -s -X POST -H "Content-Type: application/json" -d "@payload.json" "$WEBHOOK_URL" || echo "⚠️ Failed to send Discord webhook"
